# Generated by Django 3.2.9 on 2021-11-14 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_manager', '0006_asyncerrormessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrangerCausality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_lag', models.IntegerField(blank=True, null=True, verbose_name='最大滞后阶')),
                ('current_event', models.IntegerField(blank=True, null=True, verbose_name='当前事件')),
                ('current_user', models.TextField(blank=True, verbose_name='当前用户')),
                ('results', models.TextField(blank=True, null=True, verbose_name='结果')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': 'Granger因果',
                'verbose_name_plural': 'Granger因果',
            },
        ),
    ]
